networks:
  flashcard_network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: flashcard_nginx
    ports:
      - ${SERVER_PORT}:80
    links:
      - "php"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:rw
      - ./.docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - mysql
    networks:
      - flashcard_network

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: flashcard_php
    volumes:
      - ./:/var/www/html
    ports:
      - ${PHP_PORT}:9000
    networks:
      - flashcard_network

  mysql:
    image: mysql:latest
    container_name: flashcard_mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_HOST_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - flashcard_network

  mysql_test:
    image: mysql:latest
    container_name: flashcard_mysql_test
    restart: unless-stopped
    tty: true
    ports:
      - ${TEST_DB_HOST_PORT}:3307
    environment:
      MYSQL_DATABASE: ${TEST_DB_DATABASE}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TEST_DB_ROOT_PASSWORD}
      MYSQL_USER: ${TEST_DB_USERNAME}
    networks:
      - flashcard_network

  redis:
    image: redis:alpine
    container_name: flashcard_redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - flashcard_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mysql_data:
